# Generated by Django 5.0.1 on 2024-01-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFurnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persoana_de_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('companie', models.CharField(max_length=255)),
                ('cui', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.BigIntegerField()),
                ('serial_number', models.BigIntegerField()),
                ('producator', models.CharField(max_length=50)),
                ('descriere', models.CharField(max_length=255)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaAchizitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_factura', models.BigIntegerField()),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Gestiune.contactfurnizor')),
            ],
        ),
        migrations.AddField(
            model_name='contactfurnizor',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Gestiune.furnizor'),
        ),
        migrations.CreateModel(
            name='ProduseReceptionate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptie_marfa', models.CharField(max_length=2550)),
                ('cantitate', models.IntegerField()),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Gestiune.produs')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptieMarfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('receptionat_de', models.CharField(max_length=50)),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Gestiune.contactfurnizor')),
            ],
        ),
    ]
