# Generated by Django 5.0.1 on 2024-01-31 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacte'},
        ),
        migrations.AlterModelOptions(
            name='contactfurnizor',
            options={'verbose_name_plural': 'Contact Furnizori'},
        ),
        migrations.AlterModelOptions(
            name='facturaachizitie',
            options={'verbose_name_plural': 'Facturi Achizitie'},
        ),
        migrations.AlterModelOptions(
            name='furnizor',
            options={'verbose_name_plural': 'Furnizori'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterModelOptions(
            name='produsereceptionate',
            options={'verbose_name_plural': 'Produse Receptionate'},
        ),
        migrations.AlterModelOptions(
            name='receptiemarfa',
            options={'verbose_name_plural': 'Receptie Marfuri'},
        ),
        migrations.AddField(
            model_name='contact',
            name='nr_telefon',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaachizitie',
            name='valoare_factura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produs',
            name='nume_produs',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactfurnizor',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.furnizor'),
        ),
        migrations.AlterField(
            model_name='facturaachizitie',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.contactfurnizor'),
        ),
        migrations.AlterField(
            model_name='produsereceptionate',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.produs'),
        ),
        migrations.AlterField(
            model_name='receptiemarfa',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.contactfurnizor'),
        ),
    ]
