# Generated by Django 5.0.1 on 2024-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furnizor',
            options={'verbose_name_plural': 'Furnizori'},
        ),
        migrations.AddField(
            model_name='produs',
            name='nume_produs',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
    ]
