# Generated by Django 5.0.1 on 2024-01-29 18:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0002_alter_furnizor_options_produs_nume_produs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nr_telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
    ]
