# Generated by Django 5.0.1 on 2024-02-03 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0002_alter_contact_options_alter_contactfurnizor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnizor',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='furnizor',
            name='companie',
        ),
        migrations.AddField(
            model_name='facturaachizitie',
            name='data_factura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furnizor',
            name='numar_reg_com',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furnizor',
            name='telefon',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturaachizitie',
            name='valoare_factura',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='cui',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='nume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produs',
            name='ean',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='produs',
            name='serial_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
