# Generated by Django 5.0.1 on 2024-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0003_remove_furnizor_categorie_remove_furnizor_companie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnizor',
            name='adresa',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='numar_reg_com',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='nume',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='telefon',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
