# Generated by Django 5.0.1 on 2024-01-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0003_contact_nr_telefon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacte'},
        ),
        migrations.AlterModelOptions(
            name='contactfurnizor',
            options={'verbose_name_plural': 'ContactFurnizori'},
        ),
        migrations.AlterModelOptions(
            name='facturaachizitie',
            options={'verbose_name_plural': 'FacturiAchizitie'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterModelOptions(
            name='produsereceptionate',
            options={'verbose_name_plural': 'ProduseReceptionate'},
        ),
        migrations.AlterModelOptions(
            name='receptiemarfa',
            options={'verbose_name_plural': 'ReceptieMarfuri'},
        ),
    ]
