# Generated by Django 5.0.1 on 2024-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0004_alter_furnizor_adresa_alter_furnizor_numar_reg_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='cantitate_in_stoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='adresa',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='numar_reg_com',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='nume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnizor',
            name='telefon',
            field=models.CharField(default='', max_length=15),
        ),
    ]
