# Generated by Django 5.0.1 on 2024-01-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0004_alter_contact_options_alter_contactfurnizor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactfurnizor',
            options={'verbose_name_plural': 'Contact Furnizori'},
        ),
        migrations.AlterModelOptions(
            name='facturaachizitie',
            options={'verbose_name_plural': 'Facturi Achizitie'},
        ),
        migrations.AlterModelOptions(
            name='produsereceptionate',
            options={'verbose_name_plural': 'Produse Receptionate'},
        ),
        migrations.AlterModelOptions(
            name='receptiemarfa',
            options={'verbose_name_plural': 'Receptie Marfuri'},
        ),
    ]
