# Generated by Django 5.0.1 on 2024-01-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0005_alter_contactfurnizor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfurnizor',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.furnizor'),
        ),
        migrations.AlterField(
            model_name='facturaachizitie',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.contactfurnizor'),
        ),
        migrations.AlterField(
            model_name='produsereceptionate',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.produs'),
        ),
        migrations.AlterField(
            model_name='receptiemarfa',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.contactfurnizor'),
        ),
    ]
