# Generated by Django 5.0.1 on 2024-01-29 19:14

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0006_alter_contactfurnizor_furnizor_and_more'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnizor',
            name='adresa',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
