# Generated by Django 5.0.1 on 2024-02-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0006_alter_facturaachizitie_valoare_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaachizitie',
            name='furnizor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestiune.furnizor'),
        ),
    ]
