# Generated by Django 5.0.1 on 2024-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0007_alter_furnizor_adresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnizor',
            name='adresa',
            field=models.CharField(max_length=255),
        ),
    ]
